risky: true

preset: psr12

enabled:
    - alpha_ordered_imports
    - combine_consecutive_issets
    - combine_consecutive_unsets
    - const_separation
    - dir_constant
    - hash_to_slash_comment
    - native_function_casing
    - no_alias_functions
    - no_blank_lines_after_phpdoc
    - no_empty_statement
    - no_extra_consecutive_blank_lines
    - no_short_bool_cast
    - no_singleline_whitespace_before_semicolons
    - no_trailing_comma_in_singleline_array
    - no_unneeded_control_parentheses
    - no_unused_imports
    - phpdoc_no_package
    - phpdoc_scalar
    - self_accessor
    - short_array_syntax
    - single_quote
    - whitespace_after_comma_in_array
